# 5.1 Print

In [1]:
print('Ini Kelas Algoritma!')

Ini Kelas Algoritma!


In [2]:
print('Ini kelas Algoritma')

Ini kelas Algoritma


In [3]:
print('He is such a "GENIUS"')

He is such a "GENIUS"


In [ ]:
print("He is such a "GENIUS"")

In [6]:
mahasiswa_035 = 35
uang_di_dompet_035 = 100000
print(mahasiswa_035)
print(uang_di_dompet_035)
print(mahasiswa_035*uang_di_dompet_035)

35
100000
3500000


In [7]:
nama_depan_035 = 'Eza'
nama_tengah_035 = ' '
nama_belakang_035 = "Purnama"
print(nama_depan_035 + nama_tengah_035 + nama_belakang_035)

Eza Purnama


# 5.2 Input

In [9]:
nama_035 = input("Siapakah nama anda? ")
kegiatan_sekarang_035 = input('Apakah yang akan anda lakukan sekarang, ' + nama_035 +"? ")
print('Semangat ' + kegiatan_sekarang_035 +"nya yah, " + nama_035 +"!")

Siapakah nama anda? Eza
Apakah yang akan anda lakukan sekarang, Eza? Belajar
Semangat Belajarnya yah, Eza!


In [10]:
tinggi_badan_035 = input('Berapakah tinggi anda dalam cm? ')
print("Tinggi badan anda adalah " + tinggi_badan_035 + " cm")

Berapakah tinggi anda dalam cm? 170
Tinggi badan anda adalah 170 cm


# 5.3 Tipe Data pada Python

In [11]:
uang_di_dompet_035 = input("Berapakah jumlah uang di dompet anda? ")
uang_di_bank_035 = input("Berapakah jumlah uang anda di bank? ")
print("Total uang anda adalah Rp " + uang_di_dompet_035 + uang_di_bank_035)

Berapakah jumlah uang di dompet anda? 50000
Berapakah jumlah uang anda di bank? 100000
Total uang anda adalah Rp 50000100000


In [12]:
uang_di_dompet_035 = input("Berapakah jumlah uang di dompet anda? ")
uang_di_bank_035 = input("Berapakah jumlah uang anda di bank? ")
total_uang_035 = int(uang_di_dompet_035) + int(uang_di_bank_035)
print("Total uang anda adalah Rp " + str(total_uang_035))

Berapakah jumlah uang di dompet anda? 50000
Berapakah jumlah uang anda di bank? 100000
Total uang anda adalah Rp 150000


In [13]:
type(uang_di_dompet_035)

str

In [14]:
type(total_uang_035)

int

In [15]:
bilangan_satu_035 = input("Masukan bilangan pertama: ")
bilangan_kedua_035 = input("Masukan bilangan kedua: ")
jumlah_035 = float(bilangan_satu_035) + float(bilangan_kedua_035)
print("Jumlah kedua bilangan adalah " + str(jumlah_035))

Masukan bilangan pertama: 1
Masukan bilangan kedua: 2
Jumlah kedua bilangan adalah 3.0


# 5.4 Formatted String

In [16]:
nama_035 = "Vladimir"
pekerjaan_035 = 'guru'
institusi_035 = 'SD Pertiwi'
print(nama_035 + ' adalah seorang ' + pekerjaan_035 + ' di ' + institusi_035 + '.')

Vladimir adalah seorang guru di SD Pertiwi.


In [17]:
print(f'{nama_035} adalah seorang {pekerjaan_035} di {institusi_035}.')

Vladimir adalah seorang guru di SD Pertiwi.


In [18]:
print(f"{nama_035} adalah seorang {pekerjaan_035} di {institusi_035}.")

Vladimir adalah seorang guru di SD Pertiwi.


# 5.5 Strings Index

In [19]:
kelas_035 ='ini kelas algoritma'

In [20]:
print(kelas_035[0:3])

ini


In [21]:
print(kelas_035[0:-1])

ini kelas algoritm


In [22]:
print(kelas_035[5:-1])

elas algoritm


In [23]:
print(kelas_035[2:-1:3])

ieslrm


In [24]:
print(kelas_035[:-3])

ini kelas algori


In [25]:
print(kelas_035[1:])

ni kelas algoritma


In [26]:
print(kelas_035[:])

ini kelas algoritma


# 5.6 String Methods

In [27]:
judul_035 = 'Bali Surga Dunia'

In [28]:
print(len(judul_035))

16


In [29]:
judul_035.upper()

'BALI SURGA DUNIA'

In [30]:
judul_035.lower()

'bali surga dunia'

In [31]:
judul_035.find('Surga')

5

In [32]:
judul_035.find('bali')

-1

In [33]:
judul_035.replace('Bali','Indonesia')

'Indonesia Surga Dunia'

In [34]:
judul_035.replace('bali','Indonesia')

'Bali Surga Dunia'

In [35]:
print('Bali' in judul_035)

True


In [36]:
print('bali' in judul_035)

False


# 5.7 Operasi Matematika di python

In [37]:
print(2+3)
print(2-3)
print(2*3)
print(7/3)
print(7//3)
print(7%3)
print(2**3)
x=3
x+=1
print(x)
x-=2
print(x)
x*=3
print(x)

5
-1
6
2.3333333333333335
2
1
8
4
2
6


In [38]:
print(3+2)
print(3-2)
print(2*4)
print(7/4)
print(7//4)
print(8%5)
print(2**5)
x=4
x+=1
print(x)
x-=2
print(x)
x*=3
print(x)

5
1
8
1.75
1
3
32
5
3
9


In [39]:
print(5+7)
print(7-5)
print(5*7)
print(7/5)
print(5//7)
print(7%5)
print(5**7)
x=4
x+=1
print(x)
x-=2
print(x)
x*=3
print(x)

12
2
35
1.4
0
2
78125
5
3
9


# 5.8 Operator Perbandingan di Python

In [40]:
x = 3>2
print(x)
x = 2<3
print(x)
x = 3 >= 2
print(x)
x = 2 <= 3
print(x)
x = 3 == 3
print(x)
x = 3 != 4
print(x)

True
True
True
True
True
True


In [41]:
x = 2>3
print(x)
x = 3<2
print(x)
x = 2 >= 3
print(x)
x = 3 <= 2
print(x)
x = 3 == 4
print(x)
x = 3 != 3
print(x)

False
False
False
False
False
False


In [42]:
z = 5>9
print(z)
z = 5<9
print(z)
z = 9 >= 5
print(z)
z = 9 <= 5
print(z)
z = 9 == 9
print(z)
z = 9 != 5
print(z)

False
True
True
False
True
True


# 5.9 Operator Logika di Python

In [43]:
buah_manggis_035 = 10
buah_mangga_035 = 15
print(buah_manggis_035 > 8 and buah_mangga_035 < 20)

True


In [44]:
print(buah_manggis_035 < 8 or buah_mangga_035 < 20)

True


In [45]:
print(buah_manggis_035 < 8 or buah_mangga_035 > 20)

False


In [46]:
print(not (buah_manggis_035 < 8 or buah_mangga_035 > 20))

True


In [52]:
buah_durian = 5
buah_semangka = 20
print(buah_durian > 4 and buah_semangka < 30)
print(buah_durian < 4 or buah_semangka < 25)

True
True


# 5.10 Operator if di python

In [53]:
nilai = float(input("Nilai anda adalah "))
if nilai >= 80:
    print("Anda mendapat nilai A")
    print("Bagus sekali, selamat!")
if nilai < 80 and nilai >= 70:
    print("Anda mendapat nilai B")
    print("Tingkatkan prestasimu!")
if nilai >= 60 and nilai < 70:
    print("Anda mendapat nilai C")
    print("Lain kali musti lebih baik")
if nilai >= 50 and nilai < 60:
    print("Anda mendapat nilai D")
    print("Ulangi lagi tahun depan")
if nilai < 50:
    print("Anda mendapat nilai E")
    print("Sampai jumpa tahun depan")

Nilai anda adalah 100
Anda mendapat nilai A
Bagus sekali, selamat!


In [54]:
nilai = float(input("Nilai anda adalah "))
if nilai >= 80:
    print("Anda mendapat nilai A")
    print("Bagus sekali, selamat!")
elif nilai >= 70:
    print("Anda mendapat nilai B")
    print("Tingkatkan prestasimu!")
elif nilai >= 60:
    print("Anda mendapat nilai C")
    print("Lain kali musti lebih baik")
elif nilai >= 50:
    print("Anda mendapat nilai D")
    print("Ulangi lagi tahun depan")
else:
    print("Anda mendapat nilai E")
    print("Sampai jumpa tahun depan")

Nilai anda adalah 88
Anda mendapat nilai A
Bagus sekali, selamat!


Latihan: Buatlah program yang merubah tinggi badan seseorang dari cm
ke inci atau sebaliknya dari inci ke cm.

In [91]:
tinggi = float(input("Tinggimu berapa, Eza? "))
cm_atau_inci = input("Tingginya dalam cm atau inci? ")
if cm_atau_inci.upper() == 'CM':
    tinggi = tinggi*0.394
    print("Tinggi anda adalah " + str(tinggi) + " inci")
elif cm_atau_inci.upper() == "INCI" :
    tinggi = tinggi/0.394
    print(f"Tinggi anda adalah {tinggi} cm")

Tinggimu berapa, Eza? 174
Tingginya dalam cm atau inci? cm
Tinggi anda adalah 68.556 inci


# 5.11 While loop

In [55]:
a = 0
while a < 5:
    print("Angka " + str(a)+" masih dibawah 5")
    a += 1

Angka 0 masih dibawah 5
Angka 1 masih dibawah 5
Angka 2 masih dibawah 5
Angka 3 masih dibawah 5
Angka 4 masih dibawah 5


In [56]:
a = 0
while a < 5:
    print(a * '*')
    a += 1


*
**
***
****


In [61]:
a = 0
while a < 5:
    print(a * '* ')
    a += 1


* 
* * 
* * * 
* * * * 


# 5.12 list di python

In [62]:
buah_035 = ['mangga', 'pisang', 'rambutan', 'durian']
print(buah_035)

['mangga', 'pisang', 'rambutan', 'durian']


In [63]:
print(buah_035[0])

mangga


In [64]:
print(buah_035[2])

rambutan


In [65]:
print(buah_035[-1])

durian


In [66]:
print(buah_035[-2])

rambutan


In [67]:
buah_035[0] = 'salak'
print(buah_035)

['salak', 'pisang', 'rambutan', 'durian']


In [68]:
print(buah_035[0:3])

['salak', 'pisang', 'rambutan']


In [69]:
# tidak merubah list
print(buah_035)

['salak', 'pisang', 'rambutan', 'durian']


In [70]:
benda = ['meja', 'piano', 'ranting', 'dadu', 'dasi']
print(benda)

['meja', 'piano', 'ranting', 'dadu']


In [71]:
print(benda[1])

piano


# 5.13 Metoda list

In [72]:
nama = ['Wayan','Tari','Gautama']
nama.append('Jaya')
print(nama)

['Wayan', 'Tari', 'Gautama', 'Jaya']


In [73]:
nama.insert(0,'Lanang')
print(nama)

['Lanang', 'Wayan', 'Tari', 'Gautama', 'Jaya']


In [74]:
nama.remove('Wayan')
print(nama)

['Lanang', 'Tari', 'Gautama', 'Jaya']


In [75]:
print('Wayan' in nama)

False


In [76]:
print('Jaya' in nama)

True


In [77]:
print(len(nama))

4


# 5.14 For loop

In [83]:
benda = ['Tas','Lemari','Baju','Jaket','Kabel','Kipas']
for jenis in benda:
    print(jenis)

Tas
Lemari
Baju
Jaket
Kabel
Kipas


In [84]:
i = 0
while i < len(benda):
    print(benda[i])
    i+=1


Tas
Lemari
Baju
Jaket
Kabel
Kipas


# 5.15 Fungsi range

In [85]:
angka = range(8)
print(angka)

range(0, 8)


In [86]:
for isi in angka:
    print(isi)

0
1
2
3
4
5
6
7


In [87]:
for isi in range(6,12):
    print(isi)

6
7
8
9
10
11


In [89]:
for isi in range(1,13,3):
    print(isi)

1
4
7
10


Latihan 5.15
contoh program untuk mencari nilai terbesar & nilai unik dalam suatu list

In [90]:
data = [1,2,3,4,5,6,5,4,3,2,1]
terbesar = data[0]
for i in range(len(data)):
    if data[i] > terbesar:
        terbesar = data[i]
print(terbesar)

6


In [91]:
data = [1,2,3,4,5,6,5,4,3,2,1]
terbesar = data[0]
for angka in data:
    if angka > terbesar:
        terbesar = angka
print(terbesar)

6


In [92]:
angka = [1,1,2,3,4,5,6,7,7,8,7,8]
angka_unik = []
for anggota in angka:
    if anggota not in angka_unik:
        angka_unik.append(anggota)
print(angka_unik)

[1, 2, 3, 4, 5, 6, 7, 8]


# 5.16 List 2 Dimensi

In [94]:
matrik = [
    [1,2,3,4,5],
    [6,7,8,9],
    [10,11,12,13,14],
    [15,16,17,18,]
]
print(matrik)

[[1, 2, 3, 4, 5], [6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18]]


In [95]:
matrik[2]

[10, 11, 12, 13, 14]

In [96]:
matrik[1][2]

8

In [97]:
matrik[1][2]=100
print(matrik[1][2])

100


In [98]:
matrik

[[1, 2, 3, 4, 5], [6, 7, 100, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18]]

In [99]:
for baris in matrik:
    print(baris)
    for kolom in baris:
        print(kolom)

[1, 2, 3, 4, 5]
1
2
3
4
5
[6, 7, 100, 9]
6
7
100
9
[10, 11, 12, 13, 14]
10
11
12
13
14
[15, 16, 17, 18]
15
16
17
18


# 5.17 Tuples

In [100]:
angka = (0,1,1,2,4,5,6)

In [102]:
print(angka[-1])

6


In [105]:
print(angka[0:4])

(0, 1, 1, 2)


In [106]:
for isi in angka [0:4]:
    print(isi)

0
1
1
2


In [107]:
angka.count(1)

2

In [110]:
angka.index(2)

3

# 5.18 Dictionaries

In [113]:
data_orang_035 = {
    "nama" : "Ketut Dogler",
    "umur" : 12,
    "apakah_singel" : False
}

In [114]:
print(data_orang_035['nama'])

Ketut Dogler


In [115]:
angka = {
    "0" : "nol",
    "1" : "satu",
    "2" : "dua",
    "3" : "tiga",
    "4" : "empat",
    "5" : "lima",
    "6" : "enam",
    "7" : "tujuh",
    "8" : "delapan",
    "9" : "sembilan"
}

In [116]:
nomor_HP = input("Masukkan nomor HP anda ")
nomor_angka = ""
for isi in nomor_HP:
    nomor_angka += angka.get(isi) + " "
print(nomor_angka)

Masukkan nomor HP anda 082146696704
nol delapan dua satu empat enam enam sembilan enam tujuh nol empat 


# 5.19 Fungsi dalam Python

In [121]:
def full_nama(first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")

In [122]:
first_name = input("Nama depan anda adalah ")
last_name = input("Nama belakang anda adalah ")
full_nama(first_name,last_name)

Nama depan anda adalah eza
Nama belakang anda adalah purnama
Nama lengkapnya adalah eza purnama


5.19.1 Tugas Fungsi pada Python

In [123]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    return(waktu)

In [127]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [125]:
waktu_sampai (80,60)

1.3333333333333333

In [128]:
waktu_tempuh(80,60)

1.3333333333333333

In [129]:
a = waktu_sampai(80,60)
print(a)

1.3333333333333333


In [130]:
b = waktu_tempuh(80,60)
print(b)

1.3333333333333333


Latihan: Buatlah program yang menggunakan fungsi Python untuk menghitung luas segitiga, lingkaran, persegi dan persegi panjang. Selain itu berikan
peringatan bagi bidang lain yang tidak termasuk perhitungan.


In [131]:
import numpy as np

In [132]:
def luas_segitiga(alas,tinggi):
    luas = (1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari):
    luas = np.pi*(jari_jari**2)
    return luas
def luas_persegi(sisi):
    luas = sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return luas

In [138]:
jenis_bidang = input("Tulis jenis bidangnya ")
if jenis_bidang.upper() == 'SEGITIGA' :
    alas = float(input('Berapakah panjang alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas (jenis_bidang) adalah {luas}")
elif jenis_bidang.upper() == 'LINGKARAN':
    jari_jari = float(input('Berapakah panjang jari-jarinya? '))
    luas = luas_lingkaran(jari_jari)
    print(f"Luas (jenis_bidang) adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI' or (jenis_bidang.upper() == 'BUJUR SANGKAR'): 
    sisi = float(input('Berapakah panjang sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas (jenis_bidang) adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
    panjang = float(input('Berapakah panjangnya? '))
    lebar = float(input('Berapakah 1ebarnya? '))
    luas = luas_persegi_panjang(panjang,lebar)
    print(f"Luas (jenis_bidang) adalah {luas}")
else:
    print(f"Maaf bidang (jenis_bidang) yang anda masukkan tidak ada.")
    print("Pilihan cuma SEGITIGA, LINGKARAN, PERSEGI dan PERSEGI PANJANG.")
    print('Terimakasih')

Tulis jenis bidangnya persegi
Berapakah panjang sisinya? 4
Luas (jenis_bidang) adalah 16.0


# 5.20 Numpy

5.20.1 Perintah Dasar pada Numpy

In [2]:
import numpy as np

In [3]:
a = np.array([0,2,4,6,8])
print(a)

[0 2 4 6 8]


In [4]:
b = np.array([[1,3,5,7],[2,4,6,8]])
print(b)

[[1 3 5 7]
 [2 4 6 8]]


In [5]:
e = np.array([[[0,1,2,3],[4,5,6,7]],
             [[8,9,8,7],[6,5,4,3]],
             [[1,2,3,4],[5,6,7,8]]])
print(e)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [6]:
a.ndim

1

In [7]:
a.shape

(5,)

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 4)

In [10]:
e.ndim

3

In [11]:
e.shape

(3, 2, 4)

5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [12]:
d = np.array([[2,4,6,8],[1,3,5,7],[9,12,15,18]])
print(d)

[[ 2  4  6  8]
 [ 1  3  5  7]
 [ 9 12 15 18]]


In [13]:
d[0,3]

8

In [14]:
d[1,:]

array([1, 3, 5, 7])

In [15]:
d[:,2]

array([ 6,  5, 15])

In [32]:
d[0,1:3]

array([4, 6])

In [17]:
d[0,0:3:2]

array([2, 6])

In [19]:
d[0,0] = 100
print(d)

[[100   4   6   8]
 [  1   3   5   7]
 [  9  12  15  18]]


5.20.3 Matrix pada Numpy

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [25]:
np.random.rand(4,3)

array([[0.9405589 , 0.76172243, 0.29978542],
       [0.6897728 , 0.24294021, 0.39003927],
       [0.73463103, 0.82881491, 0.43261235],
       [0.4004886 , 0.09698853, 0.03509112]])

In [26]:
np.random.randint(1,10,size=(3,4))

array([[2, 1, 1, 3],
       [8, 1, 6, 5],
       [2, 3, 3, 8]])

Latihan matrik ukuran 10 x 10

In [27]:
a = np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [28]:
b = np.identity(10)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [29]:
c = 9*b
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [34]:
d = np.ones((8,8))
e = np.identity(8)*8
f = d+e
print(f)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [35]:
c[1:-1,1:-1] = f
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [36]:
g = np.identity(6)*9
c[2:-2,2:-2] = g
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [37]:
h = np.ones((4,4))*2
i = np.identity(4) * 7
j = h + i
print(j)

[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


In [39]:
c[3:-3,3:-3] = j
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [41]:
k = np.identity(2)*9
c[4:-4,4:-4] = k
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 0. 2. 0. 1. 0.]
 [0. 1. 0. 2. 0. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


5.20.4 Copy pada Numpy

In [42]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [43]:
b = a
print(b)

[1 3 5 7 9]


In [44]:
b[0] = 10
print(b)

[10  3  5  7  9]


In [45]:
print(a)

[10  3  5  7  9]


In [46]:
c = np.array([2,4,6,8,10])
print(c)

[ 2  4  6  8 10]


In [47]:
d = c.copy()
print(d)

[ 2  4  6  8 10]


In [48]:
d[0] = 20
print(d)

[20  4  6  8 10]


In [49]:
print(c)

[ 2  4  6  8 10]


5.20.5 Operasi Matematika pada Numpy

In [50]:
a+2

array([12,  5,  7,  9, 11])

In [51]:
a-2

array([8, 1, 3, 5, 7])

In [52]:
a*2

array([20,  6, 10, 14, 18])

In [53]:
a/2

array([5. , 1.5, 2.5, 3.5, 4.5])

In [54]:
a**2

array([100,   9,  25,  49,  81], dtype=int32)

In [55]:
b = np.array([2,4,6,8,10])
print(b)

[ 2  4  6  8 10]


In [56]:
a+b

array([12,  7, 11, 15, 19])

In [57]:
a-b

array([ 8, -1, -1, -1, -1])

In [58]:
a*b

array([20, 12, 30, 56, 90])

In [59]:
a/b

array([5.        , 0.75      , 0.83333333, 0.875     , 0.9       ])

In [60]:
b**a

array([      1024,         64,       7776,    2097152, 1000000000],
      dtype=int32)

In [67]:
np.sin(a)

array([-0.54402111,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849])

In [61]:
np.cos(a)

array([-0.83907153, -0.9899925 ,  0.28366219,  0.75390225, -0.91113026])

In [62]:
np.tan(a)

array([ 0.64836083, -0.14254654, -3.38051501,  0.87144798, -0.45231566])

In [63]:
np.sinh(a)

array([1.10132329e+04, 1.00178749e+01, 7.42032106e+01, 5.48316123e+02,
       4.05154190e+03])

In [64]:
np.cosh(a)

array([1.10132329e+04, 1.00676620e+01, 7.42099485e+01, 5.48317035e+02,
       4.05154203e+03])

In [65]:
np.tanh(a)

array([1.        , 0.99505475, 0.9999092 , 0.99999834, 0.99999997])

In [66]:
np.sqrt(a)

array([3.16227766, 1.73205081, 2.23606798, 2.64575131, 3.        ])

5.20.6 Perkalian Matrik pada Numpy

In [68]:
a = np.array([[1,3,5,7],[2,4,6,8]])
print(a)

[[1 3 5 7]
 [2 4 6 8]]


In [69]:
b = np.array([[9,10,11,12],[13,14,15,16]])
print(b)

[[ 9 10 11 12]
 [13 14 15 16]]


In [70]:
c = a*b
print(c)

[[  9  30  55  84]
 [ 26  56  90 128]]


In [ ]:
d = np.matmul(a,b)

In [73]:
e = np.array([[9,10],[11,12],[13,14],[15,16]])
print(e)

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [74]:
f = np.matmul(a,e)
print(f)

[[212 228]
 [260 280]]


In [ ]:
g = a*e

5.20.7 min, max dan sum pada Numpy

In [77]:
a = np.array([[2,4,6,8],
              [1,3,5,7],
              [9,10,11,12]])
print(a)

[[ 2  4  6  8]
 [ 1  3  5  7]
 [ 9 10 11 12]]


In [78]:
b = np.min(a)
print(b)

1


In [79]:
c = np.min(a,axis=0)
print(c)

[1 3 5 7]


In [80]:
d = np.min(a,axis=1)
print(d)

[2 1 9]


In [81]:
e = np.max(a)
print(e)

12


In [82]:
f = np.max(a,axis=0)
print(f)

[ 9 10 11 12]


In [83]:
g = np.max(a,axis=1)
print(g)

[ 8  7 12]


In [84]:
h = np.sum(a)
print(h)

78


In [85]:
h = np.sum(a,axis=0)
print(h)

[12 17 22 27]


In [86]:
i = np.sum(a,axis=1)
print(i)

[20 16 42]
